---
_steps: &steps
  steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - run: yarn add codecov
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: make lint
    - run: make test
    - run: make
    - run: npx codecov

version: 2
jobs:
  node:10:
    docker:
      - image: circleci/node:10
    <<: *steps
  node:latest:
    docker:
      - image: circleci/node:latest
    <<: *steps

workflows:
  version: 2
  build:
    jobs:
      - node:10
      - node:latest
